### ISSUE TITLE
ADTD.trc shows error and drawing never starts

### ISSUE THREAD

**Issue by tboydston71** [goran-mihelcic/ADTD.Net#3]
Error code is:
ADTD.Net Error: 1000 : System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Mihelcic.Net.Visio.Diagrammer.MainWindow.DrawDiagrams()

**Comment by goran-mihelcic** [comment]
Make sure to unblock zip after downoad (right click - properties- unblock)

**Comment by tboydston71** [comment]
Unblocking in "Properties" before extracting resolved the issue. Thank you!
    On Tuesday, August 27, 2024 at 08:22:56 AM CDT, goran-mihelcic ***@***.***> wrote:  
 
 


Make sure to unblock zip after downoad (right click - properties- unblock)
